### ISSUE TITLE
Error Date not found

### ISSUE THREAD

**Issue by Geezle27** [dkrahmer/MealsMenuAlexaSkill#1]
@dkrahmer thanks for this. Really like the idea and the rather simple execution of adding meals from a spreadsheet.

I followed your instructions and got confirmation that the spreadsheet was linked. However, when I went to ask for a meal, Alexa told me that
"the requested date could not be found, reason, object, object"

In noticed google has changed their script editor since you wrote your instructions, did my best to adapt them to the new design. Not sure if you have had this issue in the past or if you know of a way to fix it?

I am not a programmer but happy to get you some more info if you need it for debugging.

**Comment by dkrahmer** [comment]
@Geezle27 I have made some updates to the Template Google Sheet and the Alexa skill. There were a few date/time handling inconsistencies that should be fixed now. I am waiting for Amazon to approve my changes before the skill updates are live. Normally it takes a few days.

**Comment by dkrahmer** [comment]
The Meals Menu Alexa skill and Sheet template updates are live.
