### ISSUE TITLE
Invalid Passcode

### ISSUE THREAD

**Issue by Montanaamanda** [dkrahmer/MealsMenuAlexaSkill#2]
I followed the reddit link for help but it is broken :( I got it set up but when I try to use it Alexa says invalid pass code. So what now? lol

**Comment by dkrahmer** [comment]
You might try using a different passphrase. Alexa spells some words differently or may understand them as different words. Homonyms are especially problematic, like: reed, read, red

**Comment by Montanaamanda** [comment]
That Fixed it THANKS :)

**Comment by dkrahmer** [comment]
I'm glad you got it working!
